# Generated by Django 4.1.7 on 2023-03-22 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massages',
            name='sendtime',
            field=models.DateTimeField(blank=None, default=datetime.datetime.now, null=None),
        ),
    ]
