# Generated by Django 4.1.7 on 2023-03-23 06:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_massages_sendtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massages',
            new_name='Messages',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='massage',
            new_name='message',
        ),
    ]
